### PR TITLE
[20] Object with type cannot be recognised

### LINKED ISSUE #20: Object with type cannot be recognised
PDDL element with type cannot be recognised.
"(:objects
        bank1 - bank1 bank2 - bank2
        missionary1 - missionary1 missionary2 - missionary2 missionary3 - missionary3
        cannibal1 - cannibal1 cannibal2 - cannibal2 cannibal3 - cannibal3
        boat - boat
    )"

### PR DESCRIPTION
**Pull request by zhmff**
* Update the regular expression to remove the effect of type when parsing the domain pddl.

Resolves #20

### CODE REVIEW

**Review by YIDING-CODER — APPROVED** [review]
Approved - Tested and passed.

**Comment by nirlipo** [comment]
I can't see any changes in the server/app/vfg/parser/Domain_parser.py  beyond removing comments, and whitespaces. How this solved any issue of parsing types?

**Comment by YIDING-CODER** [comment]
> I can't see any changes in the server/app/vfg/parser/Domain_parser.py beyond removing comments, and whitespaces. How this solved any issue of parsing types?

Hi Nir,

Mengfeifei Zhang is a past student, and he implemented Pddl files in a few new domains and optimised the parser. He can not update the code using pull request, because he is not part of the Planimation repository members. 

He sent me his code and I already updated it on the GitHub. He wants to become a contributor of this repository and we tried to update some comments to the code that he wrote, but we end up with the message from CI/CD Team that only members can make the pull request.

We can just close this pull request.

Thanks,
Yi

**Comment by nirlipo** [comment]
Thanks Yi for the clarification!

**Pull request closed without merging**
