### PR TITLE
Backend PR

### PR DESCRIPTION
**Pull request by ftdzh1994**

### CODE REVIEW

**Comment by ftdzh1994** [comment]
This failure is arose due to the incorrect Docker username and password in the travis, while the image itself is successfully built.

**Comment by nirlipo** [comment]
Thanks @ftdzh1994 , can you create a PR now from feature/28-error-handling into develop? I'll review it.

**Comment by ftdzh1994** [comment]
Sorry, I was on the flight. Have done it. @nirlipo

**Comment by nirlipo** [comment]
Hi @ftdzh1994 , I hope you had a good flight and you are safe!

Can you do the PR again from the planimation branch feature... -> develop. Travis cannot check branches from forks

**Comment by ftdzh1994** [comment]
Hi @nirlipo ,  sorry I'm in China mainland and was in trouble of network connection so I hadn't got the notification and replied in time.
As several other emails saying it's successfully tested and merged, do I still need to do this?

**Comment by nirlipo** [comment]
No problem, it's already merged. Thanks!

**Pull request merged**
